### PR TITLE
enhance subscribeOnce

### PR DESCRIPTION
**Pull request by ppeeou**
In the past, subscribeOnce was launched, even though we removed the token with unsubscribe.

Even in the following cases, it has been published.
So I asked for 'pull request' :)

```js
function test(msg, data) {
  console.log('data', msg, data)
} 
const token = PubSub.subscribeOnce('test', test)

const a = PubSub.unsubscribe(token1);
PubSub.publish('test', 'hello');
```

### CODE REVIEW

**Comment by ppeeou** [comment]
ping @mroderick

**Comment by mroderick** [comment]
Sorry for the very long turnaround on this PR.

In your example, you're not unsubscribing `token`, but `token1`.

For the PR, could you add a test that would fail without your changes, i.e. a test that would show that the subscriber gets called more than once?

**Comment by ppeeou** [comment]
@mroderick 
ah .. I registered the wrong case.

this is original
```
function test(msg, data) {
    console.log("data", msg, data);
}
const token = PubSub.subscribeOnce("test", test);
const a = PubSub.unsubscribe(token);
PubSub.publish("test", "hello");
PubSub.publish("test", "hello");
```

This is executed once. even though canceled the subscription.


image

you mean, asking to register a test case?

**Comment by ppeeou** [comment]
In fact I want to change the return value of once.
token (string) like subscribe

```
    /**
    *  ...
     * @return { String }
     */
    PubSub.subscribe = function( message, func ){
        ...
        return token;
    };

    /**
     * ... 
     * @return { PubSub } 
     */
    PubSub.subscribeOnce = function( message, func ){
        var token = PubSub.subscribe( message, function(){
            ...
            if( !PubSub.unsubscribe( token ) ){
                return PubSub;
            }
            ...
        });
        return PubSub;
    };

```

But for the sake of backward compatibility, let's make return a Pubsub and add PR and test.


and also .. this is another issue...
I want to return null or  '' when the `func` part is a function.
image

**Comment by ppeeou** [comment]
Sorry for that,  It works as intended.

A long time ago, I wanted to send a PR that I wanted to manage with tokens.

Ignore the PR above.

`subscribe`'s `return value` is token, also `subscribeOnce` wanted to be a token.

**Pull request closed without merging**
