### PR TITLE
Feat: Allow "Subscribe All" option

### LINKED ISSUE #102: Allow "subscribe all"
I would like to intercept all topics. I suggest the empty string, or the wildcard character, to subscribe to all topics. Since hierarchical addressing is already there, I find quite natural to be able to use

```js
PubSub.subscribe('', (message, data) => {
// Triggered with any message
})
```
to capture all topics at once.

### PR DESCRIPTION
**Pull request by subinvarghesein**
Fixes #102

### CODE REVIEW

**Comment by trunghung** [comment]
@mroderick  can this feature be merged?  I would love to this this feature

**Comment by mroderick** [comment]
That's a lovely improvement, thank you!

Would you mind removing the changes to `package-lock.json` from the pull request?

**Comment by sleepypikachu** [comment]
@mroderick What's the issue with the package-lock.json change? Isn't that file maintained by the tooling and VCd for that reason?

**Comment by subinvarghesein** [comment]
@mroderick Currently `package.json` has the version as `1.6.0` but `package-lock.json` has version set as `1.5.8`.
Why should they be on different versions?

**Comment by TheAmazingPT** [comment]
Can I assist in this PR? I would love to have this feature released =)

**Comment by subinvarghesein** [comment]
Updated the branch to latest master. Includes reverting of `package-lock.json` file as it was updated in master.

**Comment by mroderick** [comment]
Thank you for your patience with this PR.

It looks like this PR needs another rebase before it can be merged.

**Comment by subinvarghesein** [comment]
@mroderick I will only spend time on this if you are willing to merge it in time. Otherwise, I would request someone else to pick up this work.

**Comment by margau** [comment]
Hello, any updates on this PR? Would need the feature, how can I support it?

**Comment by kidandcat** [comment]
@mroderick

**Comment by mroderick** [comment]
> @mroderick I will only spend time on this if you are willing to merge it in time. Otherwise, I would request someone else to pick up this work.

I am willing to merge it, otherwise I would have said so. Since it has conflicts with `master`, I can't merge it without a rebase though.

**Comment by 0nse** [comment]
any updates on this? This PR would be very welcome

**Comment by sleepypikachu** [comment]
I will attempt to rebase this against master.

**Comment by sleepypikachu** [comment]
Seems to merge cleanly @mroderick. Why do you think this needs rebasing?

**Comment by mroderick** [comment]
This has been published as `pubsub-js@1.9.0`. Thank you for the contributions and the patience!

**Pull request closed without merging**
