### PR TITLE
add getSubscriptions public method

### PR DESCRIPTION
**Pull request by greensleeves**

### CODE REVIEW

**Comment by mroderick** [comment]
Thank you for your pull request :)

Would you mind describing what the motivates the changes?

Also, please provide end user documentation (in `README.md`) and tests covering any expansion of the API.

**Comment by greensleeves** [comment]
@mroderick 
Thank you for your comment.
If I want to see registered events, this method would help me a lot. 
This method would help me with debugging.

**Comment by mroderick** [comment]
> This method would help me with debugging.

Couldn't you accomplish the same with setting a breakpoint?

**Comment by greensleeves** [comment]
@mroderick I have in the project a huge number of publishers and subscribers in different modules. And it was very inconvenient to set breakpoints.

**Comment by subinvarghesein** [comment]
IMHO, `messages` is an internal implementation detail which should not be exposed out. By doing so, any change to the structure of `messages` in latter versions would be a breaking change.

**Comment by mroderick** [comment]
I agree with @subinvarghesein, there are other ways of accomplishing this that do not require expanding the API and maintaining backwards compatibility with this for a long time.

**Pull request closed without merging**
