### PR TITLE
add method "subscribeOnce"，Subscribes the passed function to the pass…

### PR DESCRIPTION
**Pull request by Ryuurock**
…ed message once

### CODE REVIEW

**Comment by Ryuurock** [comment]
What time can merge it, I'm waiting for use, please

**Comment by mroderick** [comment]
Thank you for your contribution 🚀 

This has been published to npm as `pubsub-js@1.6.0`

**Comment by pedro-mass** [comment]
Any chance of making it official in the docs?

**Comment by mroderick** [comment]
@pedro-mass that would be a great first pull request :)

**Pull request merged**
